Updated the points Criteria
blurry-x-face/getsetfoss pull request #117
Opened 2019-11-10 16:55 UTC by yk1ax

Closes #112 
Updated the points criteria as mentioned in the issue #112

2019-11-10 16:55 UTC, yk1ax commented
@blurry-x-face you can review the PR

2019-11-10 19:44 UTC, dojutsu-user commented
Please add one more label, `codeburst` - 100 points

2019-11-10 20:05 UTC, yk1ax commented
@dojutsu-user what is this codeburst label

2019-11-10 20:16 UTC, dojutsu-user commented
It is for `100 points`.
Currently there are no issue which have this label on it, but we plan to open it soon. :smiley:

2019-11-10 20:21 UTC, yk1ax commented
What are the criteria for this label ???

On Mon, 11 Nov 2019, 01:46 Vaibhav Gupta, <notifications@github.com> wrote:

> It is for 100 points.
> Currently there are no issue which have this label on it, but we plan to
> open it soon. 😃
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/blurry-x-face/getsetfoss/pull/117?email_source=notifications&email_token=ANBTEW5Y64J4KFTTYQF7JPTQTBT2TA5CNFSM4JLNEONKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDVFVYY#issuecomment-552229603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANBTEW5WXXT6PTH2YXCT56TQTBT2TANCNFSM4JLNEONA>
> .
>

2019-11-11 09:58 UTC, dojutsu-user commented
@yk1ax There's no criteria... we will be opening issues of that that label soon.

2019-11-11 10:05 UTC, yk1ax commented
@dojutsu-user review this PR

2019-11-11 11:52 UTC, dojutsu-user commented
@yk1ax 
Please add `codeburst` also.

2019-11-11 20:31 UTC, yk1ax commented
#codeburst

2019-11-11 20:45 UTC, yk1ax commented
<code>codeburst</codeburst>

2019-11-11 21:19 UTC, yk1ax commented
`codeburst`

2019-11-12 07:30 UTC, dojutsu-user requested changes

2019-11-12 07:30 UTC, dojutsu-user commented on index.html
> +                    &nbsp;&nbsp;Pro: 50 points
```suggestion
                    &nbsp;&nbsp;Pro: 50 points
                    &nbsp;&nbsp;Codeburst: 100 points
```

2019-11-12 10:31 UTC, dojutsu-user approved these changes

2019-11-12 10:31 UTC, merged