Update participants.json
blurry-x-face/getsetfoss pull request #23
Opened 2019-11-03 18:03 UTC by Jagnik

2019-11-04 08:10 UTC, dojutsu-user requested changes

2019-11-04 08:10 UTC, dojutsu-user commented on Data/participants.json
>      }
```suggestion
    },
```

2019-11-04 08:11 UTC, dojutsu-user commented
You made the PR from your `master` branch. This is generally not a good practice.
Please make a separate branch for each PR.

2019-11-08 12:24 UTC, blurry-x-face commented
Due to your inactivity, I am closing this PR.

2019-11-08 12:24 UTC, closed without merging