added myself as participant
blurry-x-face/getsetfoss pull request #25
Opened 2019-11-03 18:19 UTC by WolverienG6

2019-11-04 08:06 UTC, dojutsu-user commented
Please update/sync this branch with `master` branch.

2019-11-04 17:40 UTC, rishabhshuklax requested changes
don't add new "participant" key do like this way

2019-11-04 17:40 UTC, blurry-x-face commented on Data/participants.json
>      }
```suggestion
},
{
"name":......
}
```

2019-11-08 12:26 UTC, blurry-x-face commented
Due to your inactivity, I am closing this PR.

2019-11-08 12:26 UTC, closed without merging