update participant.json
blurry-x-face/getsetfoss pull request #33
Opened 2019-11-04 08:34 UTC by narendraiiitl

2019-11-04 10:07 UTC, dojutsu-user commented
Please resolve the merge conflicts.

2019-11-05 11:09 UTC, dojutsu-user requested changes

2019-11-05 11:09 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-06 12:07 UTC, blurry-x-face commented
There's #11  already opened for the same issue, kindly do not open multiple PRs for the same issue.

2019-11-06 12:07 UTC, closed without merging