Add me as a participant
blurry-x-face/getsetfoss pull request #43
Opened 2019-11-04 10:36 UTC by the-known-anon

2019-11-05 11:20 UTC, dojutsu-user requested changes

2019-11-05 11:20 UTC, dojutsu-user commented on Data/participants.json
>      }
```suggestion
    },
```

2019-11-05 15:56 UTC, dojutsu-user commented
Please resolve the merge conflicts.

2019-11-08 12:28 UTC, blurry-x-face commented
Due to your inactivity, I am closing this PR.

2019-11-08 12:28 UTC, closed without merging