Update participants.json
blurry-x-face/getsetfoss pull request #48
Opened 2019-11-04 10:44 UTC by cuber15

\\Saloni Sharma updated as participant

2019-11-05 11:25 UTC, dojutsu-user requested changes

2019-11-05 11:25 UTC, dojutsu-user commented on Data/participants.json
>      }
```suggestion
    },
```

2019-11-05 11:25 UTC, dojutsu-user commented on Data/participants.json
> +}]
```suggestion
        }
    ]
```

2019-11-05 11:26 UTC, dojutsu-user commented
Please don't make PR from your `master` branch. This is not considered as a good practice.
Make a separate branch and then make a PR from that.

2019-11-06 12:11 UTC, blurry-x-face commented
There's #27 already opened for the same issue, kindly do not open multiple PRs for the same issue.

2019-11-06 12:11 UTC, closed without merging