added myself as participants
blurry-x-face/getsetfoss pull request #53
Opened 2019-11-04 11:40 UTC by blank-27

2019-11-05 11:33 UTC, dojutsu-user requested changes

2019-11-05 11:33 UTC, dojutsu-user commented on Data/participants.json
> +=======
```suggestion
```

2019-11-05 11:33 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-05 11:33 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-06 11:59 UTC, blurry-x-face commented
You already have #34  opened. First close that then open any new PR for the same issue.

2019-11-06 11:59 UTC, closed without merging