added myself as a participant
blurry-x-face/getsetfoss pull request #56
Opened 2019-11-04 12:46 UTC by devilcoder7

added myself as a participant

2019-11-05 11:36 UTC, dojutsu-user requested changes

2019-11-05 11:36 UTC, dojutsu-user commented on Data/participants.json
>      }
```suggestion
    },
```

2019-11-05 11:36 UTC, dojutsu-user commented on Data/participants.json
> +    },
```suggestion
    }
```

2019-11-08 12:37 UTC, blurry-x-face commented
Due to your inactivity, I am closing this PR.

2019-11-08 12:37 UTC, closed without merging