add participant
blurry-x-face/getsetfoss pull request #58
Opened 2019-11-04 18:18 UTC by sus5pect

2019-11-05 11:39 UTC, dojutsu-user commented
Please don't make PR from your `master`. This is not considered as a good practice.
Create a separate branch and then make a PR from it.

2019-11-05 11:41 UTC, dojutsu-user requested changes

2019-11-05 11:41 UTC, dojutsu-user commented on Data/participants.json
> +    "email":"yadavashu    4488@gmail.com",
There shouldn't be spaces in between email address.

2019-11-05 11:41 UTC, dojutsu-user commented on Data/participants.json
>      }
```suggestion
    },
```

2019-11-05 11:41 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-05 11:41 UTC, dojutsu-user commented on Data/participants.json
> +    "email":"yadavashu    4488@gmail.com",
```suggestion
    "email":"yadavashu4488@gmail.com",
```

2019-11-05 11:41 UTC, dojutsu-user commented on Data/participants.json
> +{
```suggestion
    {
```

2019-11-08 12:38 UTC, blurry-x-face commented
Due to your inactivity, I am closing this PR.

2019-11-08 12:38 UTC, closed without merging