add me as a participant
blurry-x-face/getsetfoss pull request #59
Opened 2019-11-04 18:48 UTC by lav-joshi

2019-11-05 11:43 UTC, dojutsu-user requested changes

2019-11-05 11:43 UTC, dojutsu-user commented on Data/participants.json
>      }
```suggestion
    },
```

2019-11-05 11:43 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-05 11:45 UTC, dojutsu-user commented
Please don't make PR from your `master` branch. This is not considered as a good practice.
Make a separate branch and then make a PR from it.

2019-11-05 12:59 UTC, lav-joshi commented
Done sir

On Tue, 5 Nov 2019, 17:15 Vaibhav Gupta, <notifications@github.com> wrote:

> Please don't make PR from your master branch. This is not considered as a
> good practice.
> Make a separate branch and then make a PR from it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/blurry-x-face/getsetfoss/pull/59?email_source=notifications&email_token=ANAZIMEBYKCYOGI73MUNYILQSFMEPA5CNFSM4JIXVH52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDCR2JY#issuecomment-549788967>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAZIMCPJFASOB4ZJEZ2UBLQSFMEPANCNFSM4JIXVH5Q>
> .
>

2019-11-05 15:58 UTC, dojutsu-user commented
Please resolve the merge conflicts.

2019-11-08 12:39 UTC, blurry-x-face commented
Make a new PR from a new branch. For now, I am closing this one.

2019-11-08 12:39 UTC, closed without merging