add me as a participant
blurry-x-face/getsetfoss pull request #60
Opened 2019-11-04 18:51 UTC by HYPER2208

2019-11-05 11:46 UTC, dojutsu-user requested changes

2019-11-05 11:46 UTC, dojutsu-user commented on Data/participants.json
> +      "githubLink": "https://github.com/HYPER2208"
Please don't edit the already added ones.
Create a separate `JSON` object.

2019-11-05 11:47 UTC, dojutsu-user commented
Please don't make PR from your `master` branch. This is not considered as a good practice.
Make a separate branch and then make a PR from it.

2019-11-08 12:40 UTC, blurry-x-face commented
Due to your inactivity, I am closing this PR.

2019-11-08 12:40 UTC, closed without merging