Branch 1.5(changes you requested are done)
blurry-x-face/getsetfoss pull request #61
Opened 2019-11-04 19:13 UTC by blank-27

2019-11-05 11:48 UTC, dojutsu-user requested changes

2019-11-05 11:48 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-05 11:48 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-05 11:48 UTC, dojutsu-user commented on Data/participants.json
> +
```suggestion
```

2019-11-05 11:48 UTC, dojutsu-user commented on Data/participants.json
> +    },
```suggestion
    }
```

2019-11-05 11:49 UTC, dojutsu-user commented
Please resolve the merge conflicts.

2019-11-05 14:13 UTC, blank-27 commented
Sorry Sir ,I don't know how to resolve merge conflict.

On Tue, Nov 5, 2019 at 5:19 PM Vaibhav Gupta <notifications@github.com>
wrote:

> Please resolve the merge conflicts.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/blurry-x-face/getsetfoss/pull/61?email_source=notifications&email_token=ANJYIZDIFVDCL2VLHPVJWWLQSFMTVA5CNFSM4JIX5KVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDCSEKY#issuecomment-549790251>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANJYIZDLQHUKNK2NPJ3ESGTQSFMTVANCNFSM4JIX5KVA>
> .
>

2019-11-05 16:02 UTC, dojutsu-user requested changes

2019-11-05 16:02 UTC, dojutsu-user commented on Data/participants.json
> +      "githubLink": "https://github.com/blank-27",
```suggestion
      "githubLink": "https://github.com/blank-27"
```

2019-11-05 16:05 UTC, dojutsu-user commented
@blank-27 
> Sorry Sir ,I don't know how to resolve merge conflict.

That's the whole point of [Get Set FOSS](https://getsetfoss.tech/). You will learn many things that are required for GSoC. You are doing great :tada:. Search your doubts on Google, it will help you a lot.

2019-11-06 11:58 UTC, blurry-x-face commented
You already have #34  opened. First close that then open any new PR for the same issue.

2019-11-06 11:58 UTC, closed without merging